### ISSUE TITLE
Improve styling on the authentication page

### ISSUE THREAD

**Issue by pm3512** [ScottyLabs/tartanhacks-registration#159]
### Description

Currently, the contrast of the title, placeholders, and links/buttons is too low:
![image](https://user-images.githubusercontent.com/42977183/209920105-06e3eacf-c761-4816-9803-257fd769837f.png)
The spacing between clickable links is too small:
![image](https://user-images.githubusercontent.com/42977183/209920253-19035ff7-c3bc-40e0-97c3-0ab93e40930a.png)

**Comment by gramliu** [comment]
Honestly, might be worth replacing the gradient background of the title with just a single darker solid color
