### ISSUE TITLE
[Feature] Update registration deadlines

### ISSUE THREAD

**Issue by anudaweerasinghe** [ScottyLabs/tartanhacks-registration#178]
### Description

See here for timeline - https://docs.google.com/document/d/12CgxQf9isI5P_VLbrpzVmf-JgFT2q6m0cesALHQhn8Q/edit

**Comment by gramliu** [comment]
Reg system doesn't currently support different deadlines for CMU and external, so I just set the current signup deadline to the earlier external deadline:
![image](https://user-images.githubusercontent.com/24856195/210192268-3b0eaa01-ed0e-4573-a5b9-b7b7c29edca2.png)
