### ISSUE TITLE
[Feature] Make dietary restrictions into a dropdown

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/tartanhacks-registration#189]
### Description

Constrain input for dietary restrictions using a list of checkboxes or dropdowns. Add `other` to include other unaccounted dietary restrictions

**Comment by pm3512** [comment]
This should be one field that supports both selecting from a list of values and typing in custom values, like this: https://stackoverflow.com/a/67235819. For more details and hints, please take a look at https://www.notion.so/scottylabs-cmu/Bootcamp-TH-Registration-and-Judging-825b4e8a30c7448a83d0bf823dd1d402?pvs=4#0971370b2b3946219214d63c9fa7628d
