### ISSUE TITLE
[Feature] Create checkin items table

### ISSUE THREAD

**Issue by pm3512** [ScottyLabs/tartanhacks-registration#204]
### Description

Create a table or list that enumerates all check-in items alongside the number of check-ins for that item

**Comment by jhong66** [comment]
There was some progress made on this feature in the old sudo repo [here](https://github.com/ScottyLabs/tartanhacks-sudo/commit/69929d2ce293cb505578866cc0a9ae89b3554500). There was also a participants table [here](https://github.com/ScottyLabs/tartanhacks-sudo/blob/main/src/components/Participants.tsx) if we want to pull that feature over.
