### ISSUE TITLE
[Bug] Clicking anywhere to the left or right of the create team button opens the form

### ISSUE THREAD

**Issue by GhostOf0days** [ScottyLabs/tartanhacks-registration#215]
### Expected Behavior

Only the create team button itself should open the form. Similar to issue #214, but occurs on both the left and right.

### Steps to Reproduce

See title.

### Device Information

Desktop/Mobile: Desktop
OS: macOS Monterey 12.3.1
Browser Version: Safari 15.4

**Comment by pm3512** [comment]
Closed by #218
