### ISSUE TITLE
[Bug] Login page requires case sensitive email

### ISSUE THREAD

**Issue by Adrastopoulos** [ScottyLabs/tartanhacks-registration#97]
### Expected Behavior

Email addresses by design are not case sensitive. However, when logging in, the address is checked for strict capitalization.

### Steps to Reproduce

Attempting to log in with capitalization different than that which was used during account creation will expose this bug. 

### Device Information

Desktop/Mobile: Desktop
OS: Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
Browser Version: Chrome Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by gramliu** [comment]
Resolved here: https://github.com/ScottyLabs/tartanhacks-backend/issues/92
